### ISSUE TITLE
Improve ruby tokens

### ISSUE THREAD

**Issue by kucho** [zarifpour/xy-zed#1]
Hello! I've used your theme in a ts codebase and it looks great! However, ruby syntax still needs a bit of love:

<img width="983" alt="image" src="https://github.com/zarifpour/xy-zed/assets/26698519/7c2f17ac-4cb0-491d-aff0-fb73e75131b4">

**Comment by zarifpour** [comment]
thank you for reporting this! will try to give it some love tonight or this weekend 😉

**Comment by zarifpour** [comment]
@kucho I'm not familiar with ruby, how does this feel to you, make sense:

![CleanShot 2024-03-07 at 23 58 29 on Zed — Untitled rb — Untitled rb@2x](https://github.com/zarifpour/xy-zed/assets/16494335/5c274536-da96-4d5e-8a93-358946f1df43)

**Comment by kucho** [comment]
> @kucho I'm not familiar with ruby, how does this feel to you — does it make sense?
> 

That's a lot better! Ship it 🚀
