### ISSUE TITLE
Contrast on unselected line numbers is unreadable.

### ISSUE THREAD

**Issue by Tenkir** [zarifpour/xy-zed#3]
The is the best theme for Zed I've found yet, so thank you!

However, the contract on the selected line numbers is so low as to be almost completely unreadable.

<img width="100" alt="Screenshot 2024-03-30 at 8 18 03 AM" src="https://github.com/zarifpour/xy-zed/assets/3649828/08e661db-7ec6-4e9c-a27b-46cea8a62b72">

**Comment by zarifpour** [comment]
Thank you, I'm glad you're enjoying it 😀 

That was intentional, but thank you for the suggestion - I'll tinker it this weekend. 

Perhaps if it's still too faded after I'm done with it, you might want to manually override it to your liking in your config.

I'll post a screenshot before I merge it.

**Comment by zarifpour** [comment]
@Tenkir what do you think?

Before:

![CleanShot 2024-03-31 at 08 41 02 on Zed — xy-zed json — zed@2x](https://github.com/zarifpour/xy-zed/assets/16494335/6a008635-58db-4f40-9a6c-271d64aa7705)

---

After:

![CleanShot 2024-03-31 at 08 39 17 on Zed — xy-zed json — zed@2x](https://github.com/zarifpour/xy-zed/assets/16494335/1b3ac4e1-d418-45b2-8066-c25e72e4f635)

**Comment by Tenkir** [comment]
From the screenshots, I'd opt for the Even Lighter, since there's a color contrast on the current line, but "After" is totally usable as far as I can tell.

**Comment by zarifpour** [comment]
PR submitted, I went with **Even lighter**, thank you for the suggestion.
