### ISSUE TITLE
[missing element] `@doc` multiline documentation comments not colored [elixir]

### ISSUE THREAD

**Issue by rojnwa** [zarifpour/xy-zed#4]
The multi-line comments in Elixir which are used for documentation purposes are not themed.
They (probably) should get the same color as regular, single-line comments (greenish).

![image](https://github.com/zarifpour/xy-zed/assets/19150352/5f694de4-addb-440f-ba71-f6f0f90807c4)

Same applies to `@moduledoc """`
![image](https://github.com/zarifpour/xy-zed/assets/19150352/c913f32d-0dd0-49f0-b24c-935e23fc0393)

**Comment by zarifpour** [comment]
Thanks for reporting this! I'll take a look and push a fix soon
